language: java
jdk:
  - openjdk8

install: true
scrips: 
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw deploy

cache:
  directories:
  - $HOME/.m2

deploy:
  -
   on:
     branch: master
   provider: tower
   
