language: java
jdk:
  - openjdk8

install: true
scrips: ./mvnw clean install

cache:
  directories:
  - $HOME/.m2
  - bash <(curl -s https://codecov.io/bash)

deploy:
  -
   on:
     branch: master
   provider: tower
   
