language: java
jdk:
  - openjdk8

install:

  - sudo pip install ansible-tower-cli

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml 
  - mvn clean verify
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

deploy:
 - provider: script
   script: .travis/stage.sh
   skip_cleanup: true
   on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
 - provider: script
   script: .travis/deploy.sh
   skip_cleanup: true
   on:
    branch: master


