language: java
jdk:
  - openjdk8

install:

  - sudo pip install ansible-tower-cli

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml 
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
  - mvn deploy

cache:
  directories:
  - $HOME/.m2

deploy:
  - provider: script
    script: "tower-cli config host tower.andyneeb.com && tower-cli config verify_ssl false && tower-cli config username $TOWER_USER && tower-cli config password $TOWER_PASSWORD && pwd"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: sh $TRAVIS_BUILD/.travis/deploy_staging.sh
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
