language: java
jdk:
  - openjdk8

env:
  - PYTHONWARNINGS=ignore
  - REPO_URL=http://95.216.233.139:8081/artifactory/libs-release
  - REPO_USER=admin
  - TOWER_URL=tower.andyneeb.com
  - TOWER_USER=admin

notifications:
  slack: ci-cd-demo:H565NR29AZLfsgsztMJG1xK3

install:

  - sudo pip install ansible-tower-cli

script:
  - cp .travis/settings.xml $HOME/.m2/settings.xml 
  - mvn verify
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

deploy:
 - provider: script
   script: .travis/stage.sh
   skip_cleanup: true
   on:
    all_branches: true
    condition: $TRAVIS_BRANCH != master
 - provider: script
   script: .travis/release.sh
   skip_cleanup: true
   on:
    branch: master
